-- TODO: un-comment this at some point when neotest works for debugging
-- Ruby/Rails code

-- local neotest = require('neotest')
-- local neotest_plenary = require('neotest-plenary')
-- local neotest_rspec = require('neotest-rspec')

-- neotest.setup {
--   adapters = {
--     neotest_plenary,
--     neotest_rspec
--   },
--   icons = {
--     running_animated = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" },
--     passed = "",
--     failed = "",
--     running = "",
--     unknown = "",
--     skipped = "",
--   }
-- }
